language_server_worse_reflection.inlay_hints.enable: true
language_server_worse_reflection.inlay_hints.types: true
language_server_worse_reflection.inlay_hints.params: true
core.min_memory_limit: 8589934592
