core.min_memory_limit: 6442450944
language_server_worse_reflection.inlay_hints.enable: true
language_server_worse_reflection.inlay_hints.params: true
language_server_worse_reflection.inlay_hints.types: true
