import = [
  # uncomment the flavour you want below:
  "~/.config/alacritty/catppuccin-mocha.toml"
  # "~/.config/alacritty/catppuccin-macchiato.toml"
  # "~/.config/alacritty/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin-latte.toml"
]

[window]
opacity = 0.95

[window.dimensions]
columns = 140
lines = 55

[font]
size = 14
normal = { family = "Hack Nerd Font" }
